# Generated by Django 5.2.5 on 2025-09-05 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id_dev',
        ),
        migrations.AddField(
            model_name='device',
            name='id_prod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dispositivos.product'),
            preserve_default=False,
        ),
    ]
