# Generated by Django 5.2.5 on 2025-09-06 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_remove_product_id_dev_device_id_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='id_prod',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='name',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='measurement',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='dispositivos.device'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='unit',
            field=models.CharField(default='kWh', max_length=20),
        ),
        migrations.AddField(
            model_name='measurement',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
