# Generated by Django 5.2.5 on 2025-09-06 20:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_remove_measurement_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='device',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='value',
        ),
        migrations.AddField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='measurement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10),
        ),
        migrations.AddField(
            model_name='measurement',
            name='idProd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispositivos.device'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='name',
            field=models.CharField(default='EcoBerry', max_length=100),
        ),
        migrations.AddField(
            model_name='measurement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
